services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=quickfra
      - POSTGRES_USER=quickfra
      - POSTGRES_PASSWORD=changeme
