name: "🐞 Bug report"
description: Create a report to help us reproduce and fix a bug.
labels: ["type:bug", "priority:medium"]
body:
  - type: markdown
    attributes:
      value: "Thanks for taking the time to help improve Quickfra!"
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: A clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: How can we reproduce the behavior?
      placeholder: |
        1. Go to '...'
        2. Run '...'
        3. See error
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Quickfra version
      placeholder: v0.3.1
  - type: dropdown
    id: os
    attributes:
      label: Operating system
      options:
        - Linux
        - macOS
        - Windows
        - Other
      - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false