name: "✨ Feature request"
description: Suggest an idea to make Quickfra better.
labels: ["type:feature", "priority:low"]
body:
  - type: markdown
    attributes:
      value: "We love new ideas! Describe your proposal."
  - type: textarea
    id: problem
    attributes:
      label: Problem to solve
      description: Describe the pain point you’re facing.
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Explain your solution, API changes, and alternatives considered.
    validations:
      required: true
  - type: dropdown
    id: impact
    attributes:
      label: Impact
      options:
        - Nice to have
        - Moderate
        - Critical
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false