#!/usr/bin/env bash

DOCKER_BASE_URL="$SOURCE_BASE_URL/docker"
SCRIPTS_BASE_URL="$SOURCE_BASE_URL/scripts"

# COOLIFY
COOLIFY_TOKEN_PATH="/root/.coolify_api_token"
COOLIFY_DEFAULT_ENVIRONMENT="production"

# SNAPPYMAIL
SNAPPYMAIL_DATA_PATH="/var/lib/snappymail"
SNAPPYMAIL_CONFIG_PATH="$SNAPPYMAIL_DATA_PATH/_data_/_default_/configs"
SNAPPYMAIL_CONFIG_FILE="$SNAPPYMAIL_CONFIG_PATH/application.ini"